version: '3.4'

services:
  daprmall.product:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #ports:
    #  - "80"

  daprmall.cart:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #ports:
    #  - "80"


  daprmall.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #ports:
    #  - "80"

